apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-models-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-0e6fc666b970325a9.efs.us-east-1.amazonaws.com   # <-- your EFS DNS
    path: /
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-models-pvc
  namespace: inference
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc-manual
